version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data/db
    expose:
      - 27017
  
  python-flask:
    build: .
    container_name: python-flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo