name: Process of Continuous Integration

on:
  push:
    branches:
      - master
      - features/*
  pull_request:

jobs:

  tests: 

    runs-on: ubuntu-latest
  
  deploy:
  
    runs-on: ubuntu-latest
    
    needs: tests
    
    if: github.ref == 'refs/heads/master'
